package(default_visibility = ["//visibility:public"])

cc_library(
  name = "cache",
  hdrs = [
    "demo_lru_cache.h",
  ],
  srcs = glob([
    "*.h",
    "*.cc",
  ]),
  deps = [
  ],
  linkopts = [
    "-pthread",
    "-ldl",
  ],
)