package(default_visibility = ["//visibility:public"])

cc_binary(
  name = "func_factory_test",
  srcs = [
    "func_factory_test.cc",
  ],
  deps = [
    "//func_factory:func_factory",
  ],
  linkopts = [
    "-pthread",
    "-ldl",
  ],
)