package(default_visibility = ["//visibility:public"])

cc_library(
  name = "func_factory",
  hdrs = [
    "func_factory.h",
  ],
  srcs = glob([
    "*.h",
    "*.cc",
  ]),
  deps = [
  ],
  linkopts = [
    "-pthread",
    "-ldl",
  ],
)